### ISSUE TITLE
roll call and easy way to add certain responses

### ISSUE THREAD

**Issue by slapdot** [uncled1023/IRCBot#15]
roll call and easy way to add certain responses

**Comment by ghost** [comment]
What do you mean roll call?

**Comment by uncled1023** [comment]
Yea, what is roll call?

**Comment by slapdot** [comment]
roll call calls all the patrons names in the room when !roll is executed

**Comment by uncled1023** [comment]
Added to 1.0

**Comment by slapdot** [comment]
Cool both features or just the roll?

**Comment by uncled1023** [comment]
i didn't quite know what you meant by certain responses.

**Comment by uncled1023** [comment]
But you can change what the bot says in the module configurations under the Roll Call tab

**Comment by slapdot** [comment]
it is not working.

**Comment by slapdot** [comment]
Someone said it has to do with an access list. The roll call. and the other
thing i meant is custom commands. Such if i wanted to execute !josh HEY
JOSH was be said

**Comment by uncled1023** [comment]
Did you copy over the config and help file as well?  The config file changed as well.  It needs the config file in order to work properly.

For the custom commands, you can always add a line to the dictionary.txt in AI like: !josh *:stuff you want it to say

I'm working on adding scripting support.

**Comment by slapdot** [comment]
Has the config file, it is not working

**Comment by uncled1023** [comment]
did you check to see what access level the rollcall command has?  Configuration>Access Levels>rollcall

**Comment by slapdot** [comment]
How would i change it to just !roll ? any option for that

**Comment by uncled1023** [comment]
You would have to edit the source and the help file to match the new command name.  I made it rollcall because I am probably going to be adding a roll command for random number generation.
