### ISSUE TITLE
[Uncled1023_Work] Adding additional strings to version sends that string to the specified nick

### ISSUE THREAD

**Issue by uncled1023** [uncled1023/IRCBot#389]

**Comment by StumblesGit** [comment]
1) .ver #/g/technology,         //channel wide ctcp
2) .ver #/g/technology :string with spaces to echo        //: VERSION"  appended to end
3a) .ver #/g/technology, 1        //echo 1 to channel
3b) .ver #/g/technology,s/1/one two three/        // echos "two" i dont know why it wouldnt echo "one" ????
