### ISSUE TITLE
Kickban excesive use of the word "man" (or other any annoying word)

### ISSUE THREAD

**Issue by Assistant** [uncled1023/IRCBot#582]
I suggest (see: request (see: demand)) a feature for combot that works as following: If someone keeps using a word that's disruptive and nerve wreaking (like "man") with a certain frequency (like more than once every 30 seconds) they should be kick banned. Optimally words should be able to be configured with different thresholds each. However, the most important part is getting rid of those fucking "man"s.

**Comment by uncled1023** [comment]
Please add a request on the current codebase as this one is deprecated.

https://github.com/uncled1023/Combot
